//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Возврат билета.
    /// </summary>
    // *** Start programmer edit section *** (ВозвратБилета CustomAttributes)

    // *** End programmer edit section *** (ВозвратБилета CustomAttributes)
    [AutoAltered()]
    [Caption("Возврат билета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВозвратБилетаE", new string[] {
            "ДатаВозврата as \'Дата возврата\'",
            "ПокупкаБилета as \'Покупка билета\'",
            "ПокупкаБилета.ПунктОтпр as \'Пункт отпр\'"}, Hidden=new string[] {
            "ПокупкаБилета.ПунктОтпр"})]
    [MasterViewDefineAttribute("ВозвратБилетаE", "ПокупкаБилета", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ПунктОтпр")]
    [View("ВозвратБилетаL", new string[] {
            "ДатаВозврата as \'Дата возврата\'",
            "ПокупкаБилета.ПунктОтпр as \'Пункт отпр\'"})]
    public class ВозвратБилета : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаВозврата = System.DateTime.Now;
        
        private IIS.Kyrs1.ПокупкаБилета fПокупкаБилета;
        
        // *** Start programmer edit section *** (ВозвратБилета CustomMembers)

        // *** End programmer edit section *** (ВозвратБилета CustomMembers)

        
        /// <summary>
        /// ДатаВозврата.
        /// </summary>
        // *** Start programmer edit section *** (ВозвратБилета.ДатаВозврата CustomAttributes)

        // *** End programmer edit section *** (ВозвратБилета.ДатаВозврата CustomAttributes)
        public virtual System.DateTime ДатаВозврата
        {
            get
            {
                // *** Start programmer edit section *** (ВозвратБилета.ДатаВозврата Get start)

                // *** End programmer edit section *** (ВозвратБилета.ДатаВозврата Get start)
                System.DateTime result = this.fДатаВозврата;
                // *** Start programmer edit section *** (ВозвратБилета.ДатаВозврата Get end)

                // *** End programmer edit section *** (ВозвратБилета.ДатаВозврата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВозвратБилета.ДатаВозврата Set start)

                // *** End programmer edit section *** (ВозвратБилета.ДатаВозврата Set start)
                this.fДатаВозврата = value;
                // *** Start programmer edit section *** (ВозвратБилета.ДатаВозврата Set end)

                // *** End programmer edit section *** (ВозвратБилета.ДатаВозврата Set end)
            }
        }
        
        /// <summary>
        /// Возврат билета.
        /// </summary>
        // *** Start programmer edit section *** (ВозвратБилета.ПокупкаБилета CustomAttributes)

        // *** End programmer edit section *** (ВозвратБилета.ПокупкаБилета CustomAttributes)
        [PropertyStorage(new string[] {
                "ПокупкаБилета"})]
        [NotNull()]
        public virtual IIS.Kyrs1.ПокупкаБилета ПокупкаБилета
        {
            get
            {
                // *** Start programmer edit section *** (ВозвратБилета.ПокупкаБилета Get start)

                // *** End programmer edit section *** (ВозвратБилета.ПокупкаБилета Get start)
                IIS.Kyrs1.ПокупкаБилета result = this.fПокупкаБилета;
                // *** Start programmer edit section *** (ВозвратБилета.ПокупкаБилета Get end)

                // *** End programmer edit section *** (ВозвратБилета.ПокупкаБилета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВозвратБилета.ПокупкаБилета Set start)

                // *** End programmer edit section *** (ВозвратБилета.ПокупкаБилета Set start)
                this.fПокупкаБилета = value;
                // *** Start programmer edit section *** (ВозвратБилета.ПокупкаБилета Set end)

                // *** End programmer edit section *** (ВозвратБилета.ПокупкаБилета Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВозвратБилетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВозвратБилетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВозвратБилетаE", typeof(IIS.Kyrs1.ВозвратБилета));
                }
            }
            
            /// <summary>
            /// "ВозвратБилетаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВозвратБилетаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВозвратБилетаL", typeof(IIS.Kyrs1.ВозвратБилета));
                }
            }
        }
    }
}
