//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Билеты.
    /// </summary>
    // *** Start programmer edit section *** (ПокупкаБилета CustomAttributes)

    // *** End programmer edit section *** (ПокупкаБилета CustomAttributes)
    [AutoAltered()]
    [Caption("Билеты")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПокупкаБилетаE", new string[] {
            "ДатаПоездки as \'Дата поездки\'",
            "ДатаПокупки as \'Дата покупки\'",
            "Место as \'Место\'",
            "ПунктОтпр as \'Пункт отпр\'",
            "ПунктНазнач as \'Пункт назнач\'",
            "ВремяПокупки as \'Время покупки\'",
            "БилетКасса as \'Билет касса\'",
            "БилетКасса.Наименование as \'Наименование\'",
            "Перевозчик as \'Перевозчик\'",
            "Перевозчик.Наименование as \'Наименование\'",
            "Клиент_ as \'Клиент_\'",
            "Клиент_.БанкСчет as \'Банк счет\'"}, Hidden=new string[] {
            "БилетКасса.Наименование",
            "Перевозчик.Наименование",
            "Клиент_.БанкСчет"})]
    [MasterViewDefineAttribute("ПокупкаБилетаE", "БилетКасса", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ПокупкаБилетаE", "Перевозчик", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ПокупкаБилетаE", "Клиент_", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "БанкСчет")]
    [View("ПокупкаБилетаL", new string[] {
            "ДатаПоездки as \'Дата поездки\'",
            "ДатаПокупки as \'Дата покупки\'",
            "Место as \'Место\'",
            "ПунктОтпр as \'Пункт отпр\'",
            "ПунктНазнач as \'Пункт назнач\'",
            "ВремяПокупки as \'Время покупки\'",
            "БилетКасса.Наименование as \'Наименование\'",
            "Перевозчик.Наименование as \'Наименование\'",
            "Клиент_.БанкСчет as \'Банк счет\'"})]
    public class ПокупкаБилета : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаПоездки;
        
        private System.DateTime fДатаПокупки = System.DateTime.Now;
        
        private int fМесто;
        
        private string fПунктОтпр;
        
        private string fПунктНазнач;
        
        private string fВремяПокупки;
        
        private IIS.Kyrs1.БилетКасса fБилетКасса;
        
        private IIS.Kyrs1.Перевозчик fПеревозчик;
        
        private IIS.Kyrs1.Клиент_ fКлиент_;
        
        // *** Start programmer edit section *** (ПокупкаБилета CustomMembers)

        // *** End programmer edit section *** (ПокупкаБилета CustomMembers)

        
        /// <summary>
        /// ВремяПокупки.
        /// </summary>
        // *** Start programmer edit section *** (ПокупкаБилета.ВремяПокупки CustomAttributes)

        // *** End programmer edit section *** (ПокупкаБилета.ВремяПокупки CustomAttributes)
        [StrLen(255)]
        public virtual string ВремяПокупки
        {
            get
            {
                // *** Start programmer edit section *** (ПокупкаБилета.ВремяПокупки Get start)

                // *** End programmer edit section *** (ПокупкаБилета.ВремяПокупки Get start)
                string result = this.fВремяПокупки;
                // *** Start programmer edit section *** (ПокупкаБилета.ВремяПокупки Get end)

                // *** End programmer edit section *** (ПокупкаБилета.ВремяПокупки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупкаБилета.ВремяПокупки Set start)

                // *** End programmer edit section *** (ПокупкаБилета.ВремяПокупки Set start)
                this.fВремяПокупки = value;
                // *** Start programmer edit section *** (ПокупкаБилета.ВремяПокупки Set end)

                // *** End programmer edit section *** (ПокупкаБилета.ВремяПокупки Set end)
            }
        }
        
        /// <summary>
        /// ДатаПоездки.
        /// </summary>
        // *** Start programmer edit section *** (ПокупкаБилета.ДатаПоездки CustomAttributes)

        // *** End programmer edit section *** (ПокупкаБилета.ДатаПоездки CustomAttributes)
        public virtual System.DateTime ДатаПоездки
        {
            get
            {
                // *** Start programmer edit section *** (ПокупкаБилета.ДатаПоездки Get start)

                // *** End programmer edit section *** (ПокупкаБилета.ДатаПоездки Get start)
                System.DateTime result = this.fДатаПоездки;
                // *** Start programmer edit section *** (ПокупкаБилета.ДатаПоездки Get end)

                // *** End programmer edit section *** (ПокупкаБилета.ДатаПоездки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупкаБилета.ДатаПоездки Set start)

                // *** End programmer edit section *** (ПокупкаБилета.ДатаПоездки Set start)
                this.fДатаПоездки = value;
                // *** Start programmer edit section *** (ПокупкаБилета.ДатаПоездки Set end)

                // *** End programmer edit section *** (ПокупкаБилета.ДатаПоездки Set end)
            }
        }
        
        /// <summary>
        /// ДатаПокупки.
        /// </summary>
        // *** Start programmer edit section *** (ПокупкаБилета.ДатаПокупки CustomAttributes)

        // *** End programmer edit section *** (ПокупкаБилета.ДатаПокупки CustomAttributes)
        public virtual System.DateTime ДатаПокупки
        {
            get
            {
                // *** Start programmer edit section *** (ПокупкаБилета.ДатаПокупки Get start)

                // *** End programmer edit section *** (ПокупкаБилета.ДатаПокупки Get start)
                System.DateTime result = this.fДатаПокупки;
                // *** Start programmer edit section *** (ПокупкаБилета.ДатаПокупки Get end)

                // *** End programmer edit section *** (ПокупкаБилета.ДатаПокупки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупкаБилета.ДатаПокупки Set start)

                // *** End programmer edit section *** (ПокупкаБилета.ДатаПокупки Set start)
                this.fДатаПокупки = value;
                // *** Start programmer edit section *** (ПокупкаБилета.ДатаПокупки Set end)

                // *** End programmer edit section *** (ПокупкаБилета.ДатаПокупки Set end)
            }
        }
        
        /// <summary>
        /// Место.
        /// </summary>
        // *** Start programmer edit section *** (ПокупкаБилета.Место CustomAttributes)

        // *** End programmer edit section *** (ПокупкаБилета.Место CustomAttributes)
        public virtual int Место
        {
            get
            {
                // *** Start programmer edit section *** (ПокупкаБилета.Место Get start)

                // *** End programmer edit section *** (ПокупкаБилета.Место Get start)
                int result = this.fМесто;
                // *** Start programmer edit section *** (ПокупкаБилета.Место Get end)

                // *** End programmer edit section *** (ПокупкаБилета.Место Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупкаБилета.Место Set start)

                // *** End programmer edit section *** (ПокупкаБилета.Место Set start)
                this.fМесто = value;
                // *** Start programmer edit section *** (ПокупкаБилета.Место Set end)

                // *** End programmer edit section *** (ПокупкаБилета.Место Set end)
            }
        }
        
        /// <summary>
        /// ПунктНазнач.
        /// </summary>
        // *** Start programmer edit section *** (ПокупкаБилета.ПунктНазнач CustomAttributes)

        // *** End programmer edit section *** (ПокупкаБилета.ПунктНазнач CustomAttributes)
        [StrLen(255)]
        public virtual string ПунктНазнач
        {
            get
            {
                // *** Start programmer edit section *** (ПокупкаБилета.ПунктНазнач Get start)

                // *** End programmer edit section *** (ПокупкаБилета.ПунктНазнач Get start)
                string result = this.fПунктНазнач;
                // *** Start programmer edit section *** (ПокупкаБилета.ПунктНазнач Get end)

                // *** End programmer edit section *** (ПокупкаБилета.ПунктНазнач Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупкаБилета.ПунктНазнач Set start)

                // *** End programmer edit section *** (ПокупкаБилета.ПунктНазнач Set start)
                this.fПунктНазнач = value;
                // *** Start programmer edit section *** (ПокупкаБилета.ПунктНазнач Set end)

                // *** End programmer edit section *** (ПокупкаБилета.ПунктНазнач Set end)
            }
        }
        
        /// <summary>
        /// ПунктОтпр.
        /// </summary>
        // *** Start programmer edit section *** (ПокупкаБилета.ПунктОтпр CustomAttributes)

        // *** End programmer edit section *** (ПокупкаБилета.ПунктОтпр CustomAttributes)
        [StrLen(255)]
        public virtual string ПунктОтпр
        {
            get
            {
                // *** Start programmer edit section *** (ПокупкаБилета.ПунктОтпр Get start)

                // *** End programmer edit section *** (ПокупкаБилета.ПунктОтпр Get start)
                string result = this.fПунктОтпр;
                // *** Start programmer edit section *** (ПокупкаБилета.ПунктОтпр Get end)

                // *** End programmer edit section *** (ПокупкаБилета.ПунктОтпр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупкаБилета.ПунктОтпр Set start)

                // *** End programmer edit section *** (ПокупкаБилета.ПунктОтпр Set start)
                this.fПунктОтпр = value;
                // *** Start programmer edit section *** (ПокупкаБилета.ПунктОтпр Set end)

                // *** End programmer edit section *** (ПокупкаБилета.ПунктОтпр Set end)
            }
        }
        
        /// <summary>
        /// Билеты.
        /// </summary>
        // *** Start programmer edit section *** (ПокупкаБилета.БилетКасса CustomAttributes)

        // *** End programmer edit section *** (ПокупкаБилета.БилетКасса CustomAttributes)
        [PropertyStorage(new string[] {
                "БилетКасса"})]
        [NotNull()]
        public virtual IIS.Kyrs1.БилетКасса БилетКасса
        {
            get
            {
                // *** Start programmer edit section *** (ПокупкаБилета.БилетКасса Get start)

                // *** End programmer edit section *** (ПокупкаБилета.БилетКасса Get start)
                IIS.Kyrs1.БилетКасса result = this.fБилетКасса;
                // *** Start programmer edit section *** (ПокупкаБилета.БилетКасса Get end)

                // *** End programmer edit section *** (ПокупкаБилета.БилетКасса Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупкаБилета.БилетКасса Set start)

                // *** End programmer edit section *** (ПокупкаБилета.БилетКасса Set start)
                this.fБилетКасса = value;
                // *** Start programmer edit section *** (ПокупкаБилета.БилетКасса Set end)

                // *** End programmer edit section *** (ПокупкаБилета.БилетКасса Set end)
            }
        }
        
        /// <summary>
        /// Билеты.
        /// </summary>
        // *** Start programmer edit section *** (ПокупкаБилета.Клиент_ CustomAttributes)

        // *** End programmer edit section *** (ПокупкаБилета.Клиент_ CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент_"})]
        [NotNull()]
        public virtual IIS.Kyrs1.Клиент_ Клиент_
        {
            get
            {
                // *** Start programmer edit section *** (ПокупкаБилета.Клиент_ Get start)

                // *** End programmer edit section *** (ПокупкаБилета.Клиент_ Get start)
                IIS.Kyrs1.Клиент_ result = this.fКлиент_;
                // *** Start programmer edit section *** (ПокупкаБилета.Клиент_ Get end)

                // *** End programmer edit section *** (ПокупкаБилета.Клиент_ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупкаБилета.Клиент_ Set start)

                // *** End programmer edit section *** (ПокупкаБилета.Клиент_ Set start)
                this.fКлиент_ = value;
                // *** Start programmer edit section *** (ПокупкаБилета.Клиент_ Set end)

                // *** End programmer edit section *** (ПокупкаБилета.Клиент_ Set end)
            }
        }
        
        /// <summary>
        /// Билеты.
        /// </summary>
        // *** Start programmer edit section *** (ПокупкаБилета.Перевозчик CustomAttributes)

        // *** End programmer edit section *** (ПокупкаБилета.Перевозчик CustomAttributes)
        [PropertyStorage(new string[] {
                "Перевозчик"})]
        [NotNull()]
        public virtual IIS.Kyrs1.Перевозчик Перевозчик
        {
            get
            {
                // *** Start programmer edit section *** (ПокупкаБилета.Перевозчик Get start)

                // *** End programmer edit section *** (ПокупкаБилета.Перевозчик Get start)
                IIS.Kyrs1.Перевозчик result = this.fПеревозчик;
                // *** Start programmer edit section *** (ПокупкаБилета.Перевозчик Get end)

                // *** End programmer edit section *** (ПокупкаБилета.Перевозчик Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПокупкаБилета.Перевозчик Set start)

                // *** End programmer edit section *** (ПокупкаБилета.Перевозчик Set start)
                this.fПеревозчик = value;
                // *** Start programmer edit section *** (ПокупкаБилета.Перевозчик Set end)

                // *** End programmer edit section *** (ПокупкаБилета.Перевозчик Set end)
            }
        }
        
        // *** Start programmer edit section *** (ПокупкаБилета.Печать CustomAttributes)

        // *** End programmer edit section *** (ПокупкаБилета.Печать CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Печать()
        {
            // *** Start programmer edit section *** (ПокупкаБилета.Печать method implementation)

            return;
            // *** End programmer edit section *** (ПокупкаБилета.Печать method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПокупкаБилетаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПокупкаБилетаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПокупкаБилетаE", typeof(IIS.Kyrs1.ПокупкаБилета));
                }
            }
            
            /// <summary>
            /// "ПокупкаБилетаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПокупкаБилетаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПокупкаБилетаL", typeof(IIS.Kyrs1.ПокупкаБилета));
                }
            }
        }
    }
}
