//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kyrs1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Транзакция_.
    /// </summary>
    // *** Start programmer edit section *** (Транзакция_ CustomAttributes)

    // *** End programmer edit section *** (Транзакция_ CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Транзакция_E", new string[] {
            "Номер as \'Номер\'",
            "ПокупкаБилета as \'Покупка билета\'",
            "ПокупкаБилета.ПунктОтпр as \'Пункт отпр\'",
            "Клиент_ as \'Клиент_\'",
            "Клиент_.БанкСчет as \'Банк счет\'",
            "ВозвратБилета as \'Возврат билета\'",
            "ВозвратБилета.ДатаВозврата as \'Дата возврата\'"}, Hidden=new string[] {
            "ПокупкаБилета.ПунктОтпр",
            "Клиент_.БанкСчет",
            "ВозвратБилета.ДатаВозврата"})]
    [MasterViewDefineAttribute("Транзакция_E", "ПокупкаБилета", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ПунктОтпр")]
    [MasterViewDefineAttribute("Транзакция_E", "Клиент_", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "БанкСчет")]
    [MasterViewDefineAttribute("Транзакция_E", "ВозвратБилета", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ДатаВозврата")]
    [View("Транзакция_L", new string[] {
            "Номер as \'Номер\'",
            "ПокупкаБилета.ПунктОтпр as \'Пункт отпр\'",
            "Клиент_.БанкСчет as \'Банк счет\'",
            "ВозвратБилета.ДатаВозврата as \'Дата возврата\'"})]
    public class Транзакция_ : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private IIS.Kyrs1.ПокупкаБилета fПокупкаБилета;
        
        private IIS.Kyrs1.Клиент_ fКлиент_;
        
        private IIS.Kyrs1.ВозвратБилета fВозвратБилета;
        
        // *** Start programmer edit section *** (Транзакция_ CustomMembers)

        // *** End programmer edit section *** (Транзакция_ CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (Транзакция_.Номер CustomAttributes)

        // *** End programmer edit section *** (Транзакция_.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (Транзакция_.Номер Get start)

                // *** End programmer edit section *** (Транзакция_.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (Транзакция_.Номер Get end)

                // *** End programmer edit section *** (Транзакция_.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Транзакция_.Номер Set start)

                // *** End programmer edit section *** (Транзакция_.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (Транзакция_.Номер Set end)

                // *** End programmer edit section *** (Транзакция_.Номер Set end)
            }
        }
        
        /// <summary>
        /// Транзакция_.
        /// </summary>
        // *** Start programmer edit section *** (Транзакция_.ВозвратБилета CustomAttributes)

        // *** End programmer edit section *** (Транзакция_.ВозвратБилета CustomAttributes)
        [PropertyStorage(new string[] {
                "ВозвратБилета"})]
        [NotNull()]
        public virtual IIS.Kyrs1.ВозвратБилета ВозвратБилета
        {
            get
            {
                // *** Start programmer edit section *** (Транзакция_.ВозвратБилета Get start)

                // *** End programmer edit section *** (Транзакция_.ВозвратБилета Get start)
                IIS.Kyrs1.ВозвратБилета result = this.fВозвратБилета;
                // *** Start programmer edit section *** (Транзакция_.ВозвратБилета Get end)

                // *** End programmer edit section *** (Транзакция_.ВозвратБилета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Транзакция_.ВозвратБилета Set start)

                // *** End programmer edit section *** (Транзакция_.ВозвратБилета Set start)
                this.fВозвратБилета = value;
                // *** Start programmer edit section *** (Транзакция_.ВозвратБилета Set end)

                // *** End programmer edit section *** (Транзакция_.ВозвратБилета Set end)
            }
        }
        
        /// <summary>
        /// Транзакция_.
        /// </summary>
        // *** Start programmer edit section *** (Транзакция_.Клиент_ CustomAttributes)

        // *** End programmer edit section *** (Транзакция_.Клиент_ CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиент_"})]
        [NotNull()]
        public virtual IIS.Kyrs1.Клиент_ Клиент_
        {
            get
            {
                // *** Start programmer edit section *** (Транзакция_.Клиент_ Get start)

                // *** End programmer edit section *** (Транзакция_.Клиент_ Get start)
                IIS.Kyrs1.Клиент_ result = this.fКлиент_;
                // *** Start programmer edit section *** (Транзакция_.Клиент_ Get end)

                // *** End programmer edit section *** (Транзакция_.Клиент_ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Транзакция_.Клиент_ Set start)

                // *** End programmer edit section *** (Транзакция_.Клиент_ Set start)
                this.fКлиент_ = value;
                // *** Start programmer edit section *** (Транзакция_.Клиент_ Set end)

                // *** End programmer edit section *** (Транзакция_.Клиент_ Set end)
            }
        }
        
        /// <summary>
        /// Транзакция_.
        /// </summary>
        // *** Start programmer edit section *** (Транзакция_.ПокупкаБилета CustomAttributes)

        // *** End programmer edit section *** (Транзакция_.ПокупкаБилета CustomAttributes)
        [PropertyStorage(new string[] {
                "ПокупкаБилета"})]
        [NotNull()]
        public virtual IIS.Kyrs1.ПокупкаБилета ПокупкаБилета
        {
            get
            {
                // *** Start programmer edit section *** (Транзакция_.ПокупкаБилета Get start)

                // *** End programmer edit section *** (Транзакция_.ПокупкаБилета Get start)
                IIS.Kyrs1.ПокупкаБилета result = this.fПокупкаБилета;
                // *** Start programmer edit section *** (Транзакция_.ПокупкаБилета Get end)

                // *** End programmer edit section *** (Транзакция_.ПокупкаБилета Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Транзакция_.ПокупкаБилета Set start)

                // *** End programmer edit section *** (Транзакция_.ПокупкаБилета Set start)
                this.fПокупкаБилета = value;
                // *** Start programmer edit section *** (Транзакция_.ПокупкаБилета Set end)

                // *** End programmer edit section *** (Транзакция_.ПокупкаБилета Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Транзакция_E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Транзакция_E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Транзакция_E", typeof(IIS.Kyrs1.Транзакция_));
                }
            }
            
            /// <summary>
            /// "Транзакция_L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Транзакция_L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Транзакция_L", typeof(IIS.Kyrs1.Транзакция_));
                }
            }
        }
    }
}
